import { useState, useEffect, useRef } from "react";
import { initializeApp } from "firebase/app";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "firebase/auth";
import { getFirestore, doc, setDoc, getDoc, updateDoc, collection, addDoc, query, orderBy, getDocs, onSnapshot } from "firebase/firestore";

const firebaseConfig={apiKey:"AIzaSyCCzFtgLd-Dn76q4MMbE8Dqs3ZhENfuR3E",authDomain:"offszn-portal.firebaseapp.com",projectId:"offszn-portal",storageBucket:"offszn-portal.firebasestorage.app",messagingSenderId:"1027879996229",appId:"1:1027879996229:web:7d709b06d0a5a07d2e8c2c"};
const app=initializeApp(firebaseConfig);const auth=getAuth(app);const db=getFirestore(app);

const ADMIN_EMAILS=["help@offsznfitness.com","contact@offsznfitness.com"];
const isAdmin=(email)=>ADMIN_EMAILS.includes(email?.toLowerCase());
const statusColor=(s)=>({active:"#4ade80",paused:"#fbbf24",inactive:"#ef4444",expired:"#ef4444",cancelled:"#ef4444"}[s]||"rgba(255,255,255,.35)");
const Toast=({msg,show})=>(<div style={{position:"fixed",bottom:100,left:"50%",transform:`translateX(-50%) translateY(${show?0:20}px)`,background:"#fff",color:"#000",padding:"12px 32px",fontSize:14,fontWeight:600,fontFamily:L,zIndex:9999,opacity:show?1:0,transition:"all .3s",pointerEvents:"none",letterSpacing:1}}>{msg}</div>);
const useToast=()=>{const[t,setT]=useState({msg:"",show:false});const show=(msg)=>{setT({msg,show:true});setTimeout(()=>setT({msg:"",show:false}),2000);};return[t,show];};
const WN="2347072654465",WU=`https://wa.me/${WN}`,CU="https://calendly.com/offsznfitness/30min";
const GM=`<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d63433.717629755476!2d3.405385486200593!3d6.444434088416819!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x843f52860d3572fd%3A0x93855861f2d34fcf!2sOff-Szn%20Mobile%20Gym%20Ltd!5e0!3m2!1sen!2sng!4v1776186010992!5m2!1sen!2sng" width="100%" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>`;
const F="'Arial Black',Impact,'Helvetica Neue',Arial,sans-serif",L="'Helvetica Neue',Arial,sans-serif";
const V=0.075,vt=p=>Math.round(p*(1+V)),fp=p=>vt(p).toLocaleString();
const LS=`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 120"><text x="200" y="70" text-anchor="middle" font-family="Arial Black,Impact,sans-serif" font-weight="900" font-size="64" fill="white" font-style="italic" letter-spacing="-2">OFF-SZN</text><text x="200" y="100" text-anchor="middle" font-family="Arial,sans-serif" font-weight="400" font-size="20" fill="white" letter-spacing="12">MOBILE</text></svg>`)}`;

const sWA=d=>{const m=encodeURIComponent(`New Sign-Up:\n\nName: ${d.name}\nLocation: ${d.location}\nGoal: ${d.goal}\nPhone: ${d.phone}`);window.location.href=`https://wa.me/${WN}?text=${m}`;};
const sPlan=(n,p)=>{const m=encodeURIComponent(`Hi Off-Szn! I'm interested in the ${n} plan (₦${p} incl. VAT). I'd like to get started.`);window.location.href=`https://wa.me/${WN}?text=${m}`;};
const ss=id=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});};
const today=()=>new Date().toISOString().split("T")[0];
const dayName=d=>["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][new Date(d).getDay()];
const weekDates=(offset=0)=>{const d=new Date();d.setDate(d.getDate()-d.getDay()+offset*7);return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);return x.toISOString().split("T")[0];});};

const useSmoothScroll=()=>{const[s,setS]=useState(0);const t=useRef(0),c=useRef(0),r=useRef(null);useEffect(()=>{const o=()=>{t.current=window.scrollY;};window.addEventListener("scroll",o,{passive:true});const a=()=>{c.current+=(t.current-c.current)*0.08;setS(c.current);r.current=requestAnimationFrame(a);};r.current=requestAnimationFrame(a);return()=>{window.removeEventListener("scroll",o);cancelAnimationFrame(r.current);};},[]);return s;};
const useInView=(th=0.15)=>{const ref=useRef(null);const[v,setV]=useState(false);useEffect(()=>{const el=ref.current;if(!el)return;const obs=new IntersectionObserver(([e])=>{if(e.isIntersecting){setV(true);obs.unobserve(el);}},{threshold:th});obs.observe(el);return()=>obs.disconnect();},[th]);return[ref,v];};
const AI=({children,delay=0,direction="up",style:s})=>{const[ref,v]=useInView(0.1);const t={up:"translateY(60px)",down:"translateY(-60px)",left:"translateX(60px)",right:"translateX(-60px)",scale:"scale(0.9)"};return<div ref={ref} style={{opacity:v?1:0,transform:v?"translate(0) scale(1)":t[direction],transition:`opacity 0.8s cubic-bezier(0.16,1,0.3,1) ${delay}s, transform 0.8s cubic-bezier(0.16,1,0.3,1) ${delay}s`,...s}}>{children}</div>;};
const Sp=({w})=><div style={{width:20,height:20,border:`2px solid ${w?"rgba(255,255,255,0.2)":"rgba(0,0,0,0.2)"}`,borderTop:`2px solid ${w?"#fff":"#000"}`,borderRadius:"50%",animation:"spin .6s linear infinite",display:"inline-block"}}><style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style></div>;
const Car=({images})=>{const[i,setI]=useState(0);const t=useRef(null);useEffect(()=>{t.current=setInterval(()=>setI(p=>(p+1)%images.length),3000);return()=>clearInterval(t.current);},[images.length]);return(<div style={{position:"relative",width:"100%",height:300,overflow:"hidden"}}>{images.map((img,j)=><div key={j} style={{position:"absolute",top:0,left:0,width:"100%",height:"100%",opacity:j===i?1:0,transform:j===i?"scale(1)":"scale(1.05)",transition:"opacity .8s,transform .8s",background:"#111",display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{color:"rgba(255,255,255,.15)",fontSize:14,letterSpacing:2}}>{img}</span></div>)}<div style={{position:"absolute",bottom:12,left:"50%",transform:"translateX(-50%)",display:"flex",gap:8,zIndex:2}}>{images.map((_,j)=><button key={j} onClick={()=>{setI(j);clearInterval(t.current);}} style={{width:j===i?24:8,height:8,background:j===i?"#fff":"rgba(255,255,255,.3)",border:"none",cursor:"pointer",transition:"all .3s",padding:0}}/>)}</div></div>);};

const LogoS=()=><img src={LS} alt="Off-Szn" style={{height:38,width:"auto",display:"block"}}/>;
const CartB=({count,onClick})=>{const[h,setH]=useState(false);return<button onClick={onClick} onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{background:"none",border:"none",cursor:"pointer",padding:4,opacity:h?.6:1,fontFamily:L,fontSize:14,fontWeight:500,color:"#fff",letterSpacing:2,whiteSpace:"nowrap",transition:"opacity .3s"}}>CART{count>0&&<span style={{marginLeft:4,background:"#fff",color:"#000",fontSize:10,fontWeight:700,width:18,height:18,borderRadius:"50%",display:"inline-flex",alignItems:"center",justifyContent:"center",verticalAlign:"middle"}}>{count}</span>}</button>;};
const WAB=()=>{const[h,setH]=useState(false);return<a href={WU} target="_blank" rel="noopener noreferrer" onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{position:"fixed",bottom:24,right:24,zIndex:9999,width:56,height:56,borderRadius:"50%",background:"#25D366",display:"flex",alignItems:"center",justifyContent:"center",boxShadow:"0 4px 12px rgba(0,0,0,.3)",cursor:"pointer",textDecoration:"none",transition:"transform .3s",transform:h?"scale(1.1)":"scale(1)"}}><svg width="28" height="28" viewBox="0 0 24 24" fill="white"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347z"/><path d="M12 0C5.373 0 0 5.373 0 12c0 2.125.553 4.121 1.523 5.86L0 24l6.335-1.652A11.943 11.943 0 0012 24c6.627 0 12-5.373 12-12S18.627 0 12 0zm0 21.82c-1.98 0-3.82-.577-5.37-1.57l-.385-.228-3.99 1.046 1.065-3.89-.252-.4A9.772 9.772 0 012.18 12c0-5.422 4.398-9.82 9.82-9.82 5.422 0 9.82 4.398 9.82 9.82 0 5.422-4.398 9.82-9.82 9.82z"/></svg></a>;};

const BP=({onClick,label,style:s,loading:ld})=>{const[h,setH]=useState(false);return<button onClick={onClick} disabled={ld} onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{padding:"16px 48px",background:ld?"rgba(255,255,255,.7)":h?"rgba(255,255,255,.85)":"#fff",color:"#000",border:"none",fontSize:15,fontWeight:600,cursor:ld?"not-allowed":"pointer",letterSpacing:2,transition:"all .3s cubic-bezier(.16,1,.3,1)",transform:h&&!ld?"scale(1.03)":"scale(1)",fontFamily:L,minHeight:52,...s}}>{ld?<Sp/>:label}</button>;};
const BO=({onClick,label,full,style:s,loading:ld})=>{const[h,setH]=useState(false);return<button onClick={onClick} disabled={ld} onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{padding:"14px 32px",background:h?"rgba(255,255,255,.08)":"transparent",color:"#fff",border:"1px solid",borderColor:h?"rgba(255,255,255,.5)":"rgba(255,255,255,.15)",fontSize:14,fontWeight:500,cursor:ld?"not-allowed":"pointer",transition:"all .3s",width:full?"100%":"auto",fontFamily:L,letterSpacing:1,...s}}>{ld?<Sp w/>:label}</button>;};

const CD=({cart,setCart,isOpen,setIsOpen})=>{const[ld,setLd]=useState(false);const tot=cart.reduce((s,i)=>s+i.price*i.qty,0);const tv=vt(tot);return(<div style={{position:"fixed",top:0,right:0,width:isOpen?"min(380px,90vw)":"0",height:"100%",background:"#0a0a0a",zIndex:1001,transition:"width .4s cubic-bezier(.16,1,.3,1)",overflow:"hidden",borderLeft:isOpen?"1px solid rgba(255,255,255,.08)":"none"}}><div style={{padding:24,height:"100%",display:"flex",flexDirection:"column",minWidth:320}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:24}}><h3 style={{fontSize:18,fontWeight:500,color:"#fff",margin:0,fontFamily:L}}>Your cart</h3><button onClick={()=>setIsOpen(false)} style={{background:"none",border:"none",color:"#fff",fontSize:24,cursor:"pointer"}}>&#10005;</button></div>{cart.length===0?<p style={{color:"rgba(255,255,255,.35)",fontSize:14,flex:1,fontFamily:L}}>Your cart is empty</p>:(<><div style={{flex:1,overflowY:"auto"}}>{cart.map((it,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"16px 0",borderBottom:"1px solid rgba(255,255,255,.06)"}}><div><p style={{color:"#fff",fontSize:14,fontWeight:500,margin:"0 0 4px",fontFamily:L}}>{it.name}</p><p style={{color:"rgba(255,255,255,.4)",fontSize:13,margin:0,fontFamily:L}}>Qty: {it.qty}</p></div><div style={{display:"flex",alignItems:"center",gap:12}}><span style={{color:"#fff",fontSize:14,fontFamily:L}}>&#8358;{(vt(it.price)*it.qty).toLocaleString()}</span><button onClick={()=>setCart(cart.filter((_,j)=>j!==i))} style={{background:"none",border:"none",color:"rgba(255,255,255,.3)",cursor:"pointer",fontSize:16}}>&#10005;</button></div></div>)}</div><div style={{borderTop:"1px solid rgba(255,255,255,.1)",paddingTop:20,marginTop:16}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{color:"rgba(255,255,255,.35)",fontSize:13,fontFamily:L}}>Subtotal</span><span style={{color:"rgba(255,255,255,.5)",fontSize:13,fontFamily:L}}>&#8358;{tot.toLocaleString()}</span></div><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{color:"rgba(255,255,255,.35)",fontSize:13,fontFamily:L}}>VAT (7.5%)</span><span style={{color:"rgba(255,255,255,.5)",fontSize:13,fontFamily:L}}>&#8358;{(tv-tot).toLocaleString()}</span></div><div style={{display:"flex",justifyContent:"space-between",marginBottom:20,marginTop:8}}><span style={{color:"rgba(255,255,255,.5)",fontSize:15,fontFamily:L}}>Total</span><span style={{color:"#fff",fontSize:20,fontWeight:600,fontFamily:L}}>&#8358;{tv.toLocaleString()}</span></div><BP onClick={()=>{setLd(true);setTimeout(()=>{setLd(false);alert("Paystack checkout");},1500);}} label={ld?null:"CHECKOUT"} style={{width:"100%"}} loading={ld}/></div></>)}</div></div>);};

const HM=({isOpen,setIsOpen,setCP,user})=>{const[su,setSU]=useState(false);const[ab,setAB]=useState(false);const its=[{l:"Home",a:()=>{setCP("home");setIsOpen(false);}},{l:"Memberships",a:()=>{setCP("memberships");setIsOpen(false);}},{l:"Store",a:()=>{setCP("store");setIsOpen(false);}}];return(<div style={{position:"fixed",top:64,left:0,width:"100%",height:isOpen?"calc(100% - 64px)":"0",background:"rgba(0,0,0,.98)",zIndex:999,overflow:"hidden",transition:"height .4s cubic-bezier(.16,1,.3,1)"}}><div style={{padding:"0 32px",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",height:"100%",gap:0}}>{its.map((it,i)=><AI key={i} delay={isOpen?i*.05:0} direction="right"><MI label={it.l} onClick={it.a}/></AI>)}<AI delay={isOpen?.15:0} direction="right"><MI label="Sign up" onClick={()=>setSU(!su)}/></AI>{su&&<><AI delay={.05} direction="right"><MI label="Quick sign up" onClick={()=>{setCP("signup");setIsOpen(false);}} sub/></AI><AI delay={.1} direction="right"><MI label="Book consultation" onClick={()=>{setCP("consultation");setIsOpen(false);}} sub/></AI></>}<AI delay={isOpen?.2:0} direction="right"><MI label="About" onClick={()=>setAB(!ab)}/></AI>{ab&&<><AI delay={.05} direction="right"><MI label="Training services" onClick={()=>{setCP("training");setIsOpen(false);}} sub/></AI><AI delay={.1} direction="right"><MI label="Virtual services" onClick={()=>{setCP("virtual");setIsOpen(false);}} sub/></AI></>}<AI delay={isOpen?.25:0} direction="right"><MI label="Client portal" onClick={()=>{setCP(user?"portal":"login");setIsOpen(false);}}/></AI>{user&&isAdmin(user.email)&&<AI delay={isOpen?.28:0} direction="right"><MI label="Coach dashboard" onClick={()=>{setCP("coach");setIsOpen(false);}}/></AI>}<AI delay={isOpen?.3:0} direction="right"><MI label="Contact" onClick={()=>{setCP("contact");setIsOpen(false);}}/></AI></div></div>);};
const MI=({label,onClick,sub})=>{const[h,setH]=useState(false);return<button onClick={onClick} onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{display:"flex",alignItems:"center",justifyContent:"center",width:"100%",padding:sub?"6px 0":"10px 0",background:"none",border:"none",cursor:"pointer",transition:"all .4s",color:h?"rgba(255,255,255,.4)":"#fff",fontFamily:F,textAlign:"center"}}><span style={{fontSize:sub?18:40,fontWeight:sub?500:700,letterSpacing:2}}>{label}</span></button>;};

const Hero=()=>{const sy=useSmoothScroll();const py=sy*.4;const op=Math.max(1-sy/600,0);const sc=1+sy*.0003;return(<section style={{minHeight:"100vh",display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",textAlign:"center",padding:"80px 24px 40px",background:"#000",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:0,left:0,width:"100%",height:"120%",background:"#000",transform:`translateY(-${py}px) scale(${sc})`}}><video autoPlay muted loop playsInline style={{position:"absolute",top:0,left:0,width:"100%",height:"100%",objectFit:"cover",opacity:.3}}><source src="" type="video/mp4"/></video><div style={{position:"absolute",top:0,left:0,width:"100%",height:"100%",background:"linear-gradient(180deg,rgba(0,0,0,.3) 0%,rgba(0,0,0,.8) 100%)"}}/></div><div style={{position:"relative",zIndex:1,maxWidth:700,opacity:op,transform:`translateY(${sy*.15}px)`}}><AI delay={.4}><h1 style={{fontSize:"clamp(64px,12vw,100px)",fontWeight:900,color:"#fff",lineHeight:1,margin:"0 0 16px",letterSpacing:-2,fontFamily:F}}>WE PULL UP.<br/>YOU LEVEL UP.</h1></AI><AI delay={.6}><p style={{fontSize:18,color:"rgba(255,255,255,.55)",margin:"0 0 12px",fontFamily:L}}>At your convenience</p></AI><AI delay={.7}><div style={{display:"flex",gap:12,justifyContent:"center",flexWrap:"wrap",margin:"0 0 40px"}}>{["Lekki","Victoria Island","Ikoyi"].map(a=><span key={a} style={{padding:"6px 16px",border:"1px solid rgba(255,255,255,.2)",fontSize:13,color:"rgba(255,255,255,.6)",letterSpacing:1,fontFamily:L}}>{a}</span>)}</div></AI><AI delay={.85}><BP onClick={()=>ss("intro-offer")} label="START NOW"/></AI></div></section>);};

const SH=({sub,title})=>(<>{sub&&<AI><h2 style={{fontSize:13,color:"rgba(255,255,255,.4)",letterSpacing:4,fontWeight:500,margin:"0 0 12px",fontFamily:L}}>{sub}</h2></AI>}{title&&<AI delay={.1}><p style={{fontSize:"clamp(28px,5vw,44px)",fontWeight:700,color:"#fff",margin:"0 0 64px",fontFamily:F}}>{title}</p></AI>}</>);
const HIW=()=>{const st=[{n:"01",t:"Book",d:"Pick your plan and schedule in under 3 minutes"},{n:"02",t:"We show up",d:"Trainers arrive with all the equipment"},{n:"03",t:"You train",d:"Personalized workout tailored to your goals"}];return(<section style={{padding:"100px 24px",background:"#000"}}><div style={{maxWidth:800,margin:"0 auto",textAlign:"center"}}><SH sub="HOW IT WORKS" title="Simple as 1-2-3"/><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:32}}>{st.map((s,i)=><AI key={i} delay={.15+i*.12}><SC {...s}/></AI>)}</div></div></section>);};
const SC=({n,t,d})=>{const[h,setH]=useState(false);return<div onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{padding:32,border:"1px solid",borderColor:h?"rgba(255,255,255,.35)":"rgba(255,255,255,.06)",transition:"all .5s",transform:h?"translateY(-8px)":"none",background:h?"rgba(255,255,255,.03)":"transparent"}}><span style={{fontSize:44,fontWeight:800,color:h?"rgba(255,255,255,.5)":"rgba(255,255,255,.08)",fontFamily:F}}>{n}</span><h3 style={{fontSize:20,fontWeight:600,color:"#fff",margin:"16px 0 8px",fontFamily:L}}>{t}</h3><p style={{fontSize:14,color:"rgba(255,255,255,.4)",lineHeight:1.6,margin:0,fontFamily:L}}>{d}</p></div>;};

const IO=()=>{const[ld,setLd]=useState(false);const bp=45000;return(<section id="intro-offer" style={{padding:"100px 24px",background:"#000",borderTop:"1px solid rgba(255,255,255,.04)"}}><div style={{maxWidth:600,margin:"0 auto",textAlign:"center"}}><AI><div style={{display:"inline-block",padding:"4px 14px",background:"rgba(255,255,255,.05)",marginBottom:16,fontSize:12,color:"rgba(255,255,255,.5)",letterSpacing:2,fontFamily:L}}>LIMITED OFFER</div></AI><AI delay={.1}><h2 style={{fontSize:"clamp(32px,6vw,48px)",fontWeight:700,color:"#fff",margin:"0 0 8px",fontFamily:F}}>3-session starter pack</h2></AI><AI delay={.2} direction="scale"><div style={{margin:"24px 0"}}><span style={{fontSize:60,fontWeight:800,color:"#fff",fontFamily:F}}>&#8358;{fp(bp)}</span><p style={{fontSize:12,color:"rgba(255,255,255,.25)",marginTop:4,fontFamily:L}}>incl. 7.5% VAT</p></div></AI><AI delay={.35}><div style={{display:"flex",flexDirection:"column",gap:12,margin:"32px auto",maxWidth:320,textAlign:"left"}}>{["3 personal training sessions","Full equipment provided","Train anywhere in our radius","Customized workout plan"].map((f,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:10}}><span style={{color:"#fff"}}>&#10003;</span><span style={{color:"rgba(255,255,255,.55)",fontSize:14,fontFamily:L}}>{f}</span></div>)}</div></AI><AI delay={.45}><BP onClick={()=>{setLd(true);setTimeout(()=>{setLd(false);window.location.href=`https://wa.me/${WN}?text=${encodeURIComponent("Hi Off-Szn! I'd like to buy the 3-Session Starter Pack (₦"+fp(bp)+" incl. VAT).")}`;},1000);}} label="BUY 3-PACK NOW" loading={ld} style={{marginTop:16}}/></AI></div></section>);};

const RS=()=>{const r=[{n:"Tunde A.",d:"8 weeks",t:"Lost 12kg. Training at home changed everything."},{n:"Chioma O.",d:"12 weeks",t:"Zero gym experience to completing a 5K."},{n:"Emeka N.",d:"6 weeks",t:"Built lean muscle with a crazy work schedule."}];return(<section style={{padding:"100px 24px",background:"#000",borderTop:"1px solid rgba(255,255,255,.04)"}}><div style={{maxWidth:900,margin:"0 auto",textAlign:"center"}}><SH sub="REAL RESULTS" title="Our clients speak for us"/><AI delay={.2}><Car images={["WORKOUT 1","TRAINING 2","COMMUNITY 3","OUTDOOR 4"]}/></AI><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:24,marginTop:40}}>{r.map((x,i)=><AI key={i} delay={.1+i*.1}><div style={{border:"1px solid rgba(255,255,255,.06)",overflow:"hidden"}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",height:200}}><div style={{background:"#111",display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,color:"rgba(255,255,255,.2)",fontFamily:L}}>Before</div><div style={{background:"#0a0a0a",display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,color:"rgba(255,255,255,.2)",fontFamily:L}}>After</div></div><div style={{padding:20}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><span style={{fontWeight:600,color:"#fff",fontSize:15,fontFamily:L}}>{x.n}</span><span style={{fontSize:12,color:"rgba(255,255,255,.4)",fontFamily:L}}>{x.d}</span></div><p style={{fontSize:13,color:"rgba(255,255,255,.35)",lineHeight:1.6,margin:0,fontFamily:L}}>"{x.t}"</p></div></div></AI>)}</div></div></section>);};

const MP=()=>{const[at,setAT]=useState(0);const tabs=["One-off","Monthly (trainer+equip)","Monthly (trainer only)"];const d0=[{n:"1:1 Trainer+Equip",s:"Home (45-60min)",p:35000,f:["Personal trainer","Full equipment","Custom workout","Your location"]},{n:"1:1 Trainer Only",s:"Home (45-60min)",p:30000,f:["Personal trainer","Own equipment","Custom workout","Your location"]},{n:"1:1 Trainer Only",s:"Gym (45-60min)",p:25000,f:["Personal trainer","Gym equipment","Custom workout","Meet at gym"]},{n:"Virtual Session",s:"Online (45-60min)",p:25000,f:["Video call","Form correction","Custom workout","Train anywhere"]}];const d1=[{n:"2x/week",s:"8 sessions/mo",p:200000,f:["Trainer","Full equipment","Progress tracking","WhatsApp support"]},{n:"3x/week",s:"12 sessions/mo",p:300000,f:["Trainer","Full equipment","Progress tracking","Nutrition guidance","Priority scheduling"],h:true},{n:"5x/week",s:"20 sessions/mo",p:500000,f:["Trainer","Full equipment","Progress tracking","Nutrition guidance","Dedicated trainer","24/7 WhatsApp"]}];const d2=[{n:"2x/week",s:"8 sessions/mo",p:144000,f:["Trainer","Custom workouts","Progress tracking","WhatsApp support"]},{n:"3x/week",s:"12 sessions/mo",p:216000,f:["Trainer","Custom workouts","Progress tracking","Nutrition guidance","Priority scheduling"],h:true},{n:"5x/week",s:"20 sessions/mo",p:360000,f:["Trainer","Custom workouts","Progress tracking","Nutrition guidance","Dedicated trainer","24/7 WhatsApp"]}];const dd=[d0,d1,d2];return(<PW t="Memberships" st="Choose your plan"><div style={{maxWidth:1000,margin:"0 auto"}}><AI><div style={{display:"flex",gap:0,marginBottom:48,justifyContent:"center",flexWrap:"wrap"}}>{tabs.map((t,i)=><button key={i} onClick={()=>setAT(i)} style={{padding:"12px 24px",background:i===at?"#fff":"transparent",color:i===at?"#000":"rgba(255,255,255,.4)",border:"1px solid",borderColor:i===at?"#fff":"rgba(255,255,255,.1)",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:L,letterSpacing:1}}>{t.toUpperCase()}</button>)}</div></AI><div style={{display:"grid",gridTemplateColumns:`repeat(auto-fit,minmax(${at===0?"200px":"250px"},1fr))`,gap:24}}>{dd[at].map((p,i)=><AI key={`${at}-${i}`} delay={i*.1}><PC {...p}/></AI>)}</div><AI delay={.3}><div style={{textAlign:"center",marginTop:48,padding:24,border:"1px solid rgba(255,255,255,.06)"}}><p style={{color:"rgba(255,255,255,.5)",fontSize:14,fontFamily:L}}>Consultation fee</p><span style={{fontSize:28,fontWeight:700,color:"#fff",fontFamily:F}}>&#8358;{fp(20000)}</span><p style={{fontSize:12,color:"rgba(255,255,255,.25)",marginTop:4,fontFamily:L}}>incl. 7.5% VAT</p></div></AI></div></PW>);};
const PC=({n,s,p,f,h:hl})=>{const[h,setH]=useState(false);const pv=fp(p);return(<div onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{border:hl?"2px solid #fff":"1px solid rgba(255,255,255,.06)",padding:28,transition:"all .5s",transform:h?"translateY(-8px)":"none",background:h?"rgba(255,255,255,.03)":"transparent",position:"relative",display:"flex",flexDirection:"column"}}>{hl&&<div style={{position:"absolute",top:-12,left:"50%",transform:"translateX(-50%)",background:"#fff",color:"#000",fontSize:11,fontWeight:600,padding:"4px 16px",fontFamily:L}}>POPULAR</div>}<h3 style={{fontSize:17,fontWeight:600,color:"#fff",margin:"0 0 4px",fontFamily:L}}>{n}</h3>{s&&<p style={{fontSize:12,color:"rgba(255,255,255,.35)",margin:"0 0 16px",fontFamily:L}}>{s}</p>}<div style={{margin:"0 0 4px"}}><span style={{fontSize:30,fontWeight:700,color:"#fff",fontFamily:F}}>&#8358;{pv}</span></div><p style={{fontSize:11,color:"rgba(255,255,255,.25)",margin:"0 0 20px",fontFamily:L}}>incl. 7.5% VAT</p><div style={{display:"flex",flexDirection:"column",gap:10,marginBottom:24,flex:1}}>{f.map((x,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:8}}><span style={{color:"#fff",fontSize:12}}>&#10003;</span><span style={{color:"rgba(255,255,255,.45)",fontSize:13,fontFamily:L}}>{x}</span></div>)}</div>{hl?<BP onClick={()=>sPlan(n+(s?" ("+s+")":""),pv)} label="Get started" style={{width:"100%",padding:"12px"}}/>:<BO onClick={()=>sPlan(n+(s?" ("+s+")":""),pv)} label="Get started" full/>}</div>);};

const SP=({cart,setCart})=>{const pr=[{n:"Off-Szn Performance Tee",p:15000,i:"T"},{n:"Off-Szn Training Shorts",p:18000,i:"S"},{n:"Off-Szn Shaker Bottle",p:8000,i:"B"},{n:"Off-Szn Resistance Band Set",p:12000,i:"R"}];const ac=x=>{const e=cart.findIndex(i=>i.name===x.n);if(e>=0){const u=[...cart];u[e].qty+=1;setCart(u);}else setCart([...cart,{name:x.n,price:x.p,qty:1}]);};return(<PW t="Store" st="Gear up for greatness"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:24,maxWidth:900,margin:"0 auto"}}>{pr.map((x,i)=><AI key={i} delay={i*.1}><PrC n={x.n} p={x.p} img={x.i} onAdd={()=>ac(x)}/></AI>)}</div></PW>);};
const PrC=({n,p,img,onAdd})=>{const[h,setH]=useState(false);const[a,setA]=useState(false);return(<div onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{border:"1px solid",borderColor:h?"rgba(255,255,255,.35)":"rgba(255,255,255,.06)",overflow:"hidden",transition:"all .5s",transform:h?"translateY(-6px)":"none",cursor:"pointer"}}><div style={{height:200,background:"#111",display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:48,color:"rgba(255,255,255,.06)",fontWeight:800,transition:"transform .5s",transform:h?"scale(1.2) rotate(-5deg)":"scale(1)"}}>{img}</span></div><div style={{padding:16}}><p style={{fontSize:14,fontWeight:600,color:"#fff",margin:"0 0 4px",fontFamily:L}}>{n}</p><p style={{fontSize:14,color:"rgba(255,255,255,.5)",fontWeight:600,margin:"0 0 2px",fontFamily:L}}>&#8358;{fp(p)}</p><p style={{fontSize:11,color:"rgba(255,255,255,.25)",margin:"0 0 12px",fontFamily:L}}>incl. VAT</p><BO onClick={()=>{onAdd();setA(true);setTimeout(()=>setA(false),1200);}} label={a?"Added!":"Add to cart"} full/></div></div>);};

const SUP=({setCP})=>{const[f,setF]=useState({name:"",location:"",goal:"",phone:""});const[done,setDone]=useState(false);const[ld,setLd]=useState(false);const[er,setEr]=useState({});if(done)return(<PW t="" st=""><AI direction="scale"><div style={{textAlign:"center",maxWidth:500,margin:"0 auto"}}><div style={{width:80,height:80,background:"rgba(255,255,255,.05)",display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 24px",fontSize:36,color:"#fff"}}>&#10003;</div><h2 style={{fontSize:32,fontWeight:700,color:"#fff",margin:"0 0 12px",fontFamily:F}}>You're in!</h2><p style={{color:"rgba(255,255,255,.4)",fontSize:16,margin:"0 0 32px",fontFamily:L}}>Welcome, {f.name}. Details sent via WhatsApp.</p><BP onClick={()=>setCP("home")} label="Back to home"/></div></AI></PW>);const fds=[{l:"Name",k:"name",ph:"Full name",t:"text"},{l:"Location",k:"location",ph:"e.g. Lekki Phase 1",t:"text"},{l:"Fitness goal",k:"goal",ph:"e.g. Lose weight",t:"text"},{l:"Phone",k:"phone",ph:"+234 800 000 0000",t:"tel"}];return(<PW t="Sign up" st="Get started in under 3 minutes"><div style={{maxWidth:440,margin:"0 auto"}}>{fds.map((x,i)=><AI key={x.k} delay={i*.08}><div style={{marginBottom:20}}><label style={{display:"block",fontSize:12,color:"rgba(255,255,255,.35)",marginBottom:6,fontFamily:L}}>{x.l}{x.k!=="goal"&&<span style={{color:"rgba(255,255,255,.2)"}}> *</span>}</label><input type={x.t} placeholder={x.ph} value={f[x.k]} onChange={e=>{setF({...f,[x.k]:e.target.value});if(er[x.k])setEr({...er,[x.k]:null});}} style={{width:"100%",padding:"14px 16px",background:"rgba(255,255,255,.03)",border:`1px solid ${er[x.k]?"rgba(255,100,100,.5)":"rgba(255,255,255,.08)"}`,color:"#fff",fontSize:15,outline:"none",boxSizing:"border-box",fontFamily:L}}/>{er[x.k]&&<p style={{color:"rgba(255,100,100,.7)",fontSize:12,marginTop:4,fontFamily:L}}>{er[x.k]}</p>}</div></AI>)}<AI delay={.35}><BP onClick={()=>{const e={};if(!f.name.trim())e.name="Required";if(!f.phone.trim())e.phone="Required";if(!f.location.trim())e.location="Required";if(Object.keys(e).length){setEr(e);return;}setEr({});setLd(true);setTimeout(()=>{sWA(f);setLd(false);setDone(true);},1000);}} label="Complete sign up" loading={ld} style={{width:"100%",marginTop:8}}/></AI></div></PW>);};

const CSP=()=>(<PW t="Book a consultation" st={`Schedule a call — \u20A6${fp(20000)} incl. VAT`}><AI><div style={{maxWidth:700,margin:"0 auto",textAlign:"center"}}><div style={{border:"1px solid rgba(255,255,255,.06)",overflow:"hidden",minHeight:500}}><iframe src={CU} width="100%" height="500" frameBorder="0" style={{border:"none",background:"#111"}} title="Calendly"/></div></div></AI></PW>);
const TP=()=>(<PW t="Training services" st="What we bring to your doorstep"><div style={{maxWidth:700,margin:"0 auto"}}>{[{t:"Personal training",d:"1-on-1 sessions at your location. Fully equipped."},{t:"Group sessions",d:"Train with friends. Up to 4 per session."},{t:"Corporate fitness",d:"Wellness at your office. On your premises, on your terms."}].map((x,i)=><AI key={i} delay={i*.1}><HC t={x.t} d={x.d}/></AI>)}<AI delay={.3}><div style={{marginTop:40,padding:32,border:"1px solid rgba(255,255,255,.06)",textAlign:"center"}}><h3 style={{color:"rgba(255,255,255,.3)",fontSize:13,letterSpacing:2,margin:"0 0 16px",fontFamily:L}}>SERVICE RADIUS</h3><div style={{width:"100%",height:300,overflow:"hidden"}} dangerouslySetInnerHTML={{__html:GM}}/></div></AI></div></PW>);
const VP=({setCP})=>(<PW t="Virtual services" st="Train from anywhere"><div style={{maxWidth:700,margin:"0 auto"}}>{[{t:"Live virtual training",d:"Real-time video sessions. Full coaching and form correction."},{t:"Custom programs",d:"Weekly workout programs. Video guides and check-ins."},{t:"Nutrition guidance",d:"General guidance tailored to your goals and lifestyle."}].map((x,i)=><AI key={i} delay={i*.1}><HC t={x.t} d={x.d}/></AI>)}<AI delay={.3}><div style={{textAlign:"center",marginTop:48}}><BP onClick={()=>setCP("signup")} label="Sign up for virtual"/></div></AI></div></PW>);
const HC=({t,d})=>{const[h,setH]=useState(false);return<div onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{border:"1px solid",borderColor:h?"rgba(255,255,255,.35)":"rgba(255,255,255,.06)",padding:24,transition:"all .4s",background:h?"rgba(255,255,255,.02)":"transparent",transform:h?"translateX(8px)":"none",marginBottom:24}}><h3 style={{fontSize:17,fontWeight:600,color:"#fff",margin:"0 0 8px",fontFamily:L}}>{t}</h3><p style={{fontSize:14,color:"rgba(255,255,255,.4)",lineHeight:1.7,margin:0,fontFamily:L}}>{d}</p></div>;};
const CTP=()=>(<PW t="Contact us" st="We'd love to hear from you"><div style={{maxWidth:500,margin:"0 auto",textAlign:"center"}}><AI><a href={WU} target="_blank" rel="noopener noreferrer" style={{display:"flex",alignItems:"center",justifyContent:"center",padding:"18px 32px",background:"#fff",textDecoration:"none",color:"#000",fontWeight:600,fontSize:15,marginBottom:24,fontFamily:L,letterSpacing:1}}>Chat on WhatsApp</a></AI>{[{l:"Email",v:"contact@offsznfitness.com",u:"mailto:contact@offsznfitness.com"},{l:"Support",v:"help@offsznfitness.com",u:"mailto:help@offsznfitness.com"},{l:"Instagram",v:"@Off_sznmobile",u:"https://instagram.com/Off_sznmobile"},{l:"Location",v:"Lekki, VI, Ikoyi — Lagos"}].map((c,i)=><AI key={i} delay={.1+i*.08}><div style={{display:"flex",justifyContent:"space-between",padding:"12px 0",borderBottom:"1px solid rgba(255,255,255,.05)"}}><span style={{color:"rgba(255,255,255,.3)",fontSize:14,fontFamily:L}}>{c.l}</span>{c.u?<a href={c.u} target="_blank" rel="noopener noreferrer" style={{color:"#fff",fontSize:14,fontWeight:500,textDecoration:"none",fontFamily:L}}>{c.v}</a>:<span style={{color:"#fff",fontSize:14,fontWeight:500,fontFamily:L}}>{c.v}</span>}</div></AI>)}</div></PW>);

const FL2=({l,onClick})=>{const[h,setH]=useState(false);return<button onClick={onClick} onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{background:"none",border:"none",color:h?"rgba(255,255,255,.6)":"rgba(255,255,255,.35)",fontSize:12,fontWeight:500,letterSpacing:2,cursor:"pointer",padding:0,fontFamily:L}}>{l}</button>;};
const Ftr=({setCP})=>(<footer style={{padding:"80px 32px 40px",background:"#000",borderTop:"1px solid rgba(255,255,255,.04)"}}><div style={{maxWidth:1200,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",flexWrap:"wrap",gap:40,marginBottom:48}}><div style={{display:"grid",gridTemplateColumns:"repeat(3,auto)",gap:"20px 64px"}}><FL2 l="MEMBERSHIP" onClick={()=>setCP("memberships")}/><FL2 l="CLASSES" onClick={()=>setCP("training")}/><FL2 l="PARTNERSHIPS" onClick={()=>window.open(WU,"_blank")}/><FL2 l="TRAINING" onClick={()=>setCP("training")}/><FL2 l="ABOUT" onClick={()=>setCP("training")}/><FL2 l="CONTACT US" onClick={()=>setCP("contact")}/><FL2 l="STORE" onClick={()=>setCP("store")}/><FL2 l="PRESS" onClick={()=>window.open(WU,"_blank")}/></div><div style={{display:"flex",flexDirection:"column",gap:20,alignItems:"flex-end"}}><FL2 l="TIKTOK" onClick={()=>window.open("https://tiktok.com","_blank")}/><FL2 l="INSTAGRAM" onClick={()=>window.open("https://instagram.com/Off_sznmobile","_blank")}/></div></div><div style={{borderTop:"1px solid rgba(255,255,255,.08)",paddingTop:24,display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:16}}><div style={{display:"flex",gap:32}}>{["PRIVACY","POLICIES","TERMS"].map(x=><span key={x} style={{color:"rgba(255,255,255,.2)",fontSize:11,letterSpacing:2,fontFamily:L}}>{x}</span>)}</div><span style={{color:"rgba(255,255,255,.2)",fontSize:11,letterSpacing:2,fontFamily:L}}>&copy;2024 OFF-SZN MOBILE GYM</span></div></div></footer>);

/* ========== CLIENT PORTAL ========== */
const LP=({setCP})=>{const[reg,setReg]=useState(false);const[em,setEm]=useState("");const[pw,setPw]=useState("");const[nm,setNm]=useState("");const[ph,setPh]=useState("");const[ld,setLd]=useState(false);const[er,setEr]=useState("");
const go=async()=>{setEr("");setLd(true);try{if(reg){if(!nm.trim()||!ph.trim()){setEr("Name and phone required");setLd(false);return;}const cr=await createUserWithEmailAndPassword(auth,em,pw);await setDoc(doc(db,"clients",cr.user.uid),{name:nm,email:em,phone:ph,createdAt:today(),subscription:{plan:"None",status:"inactive",startDate:null,endDate:null},progress:{weight:[],measurements:[]},program:{current:"No program assigned yet",workouts:[]},messages:[],workoutLogs:[]});}else{await signInWithEmailAndPassword(auth,em,pw);}setCP("portal");}catch(e){const m=e.code==="auth/email-already-in-use"?"Email already registered.":e.code==="auth/wrong-password"||e.code==="auth/invalid-credential"?"Incorrect email or password.":e.code==="auth/weak-password"?"Password must be 6+ characters.":"Something went wrong.";setEr(m);}setLd(false);};
return(<PW t="Client portal" st={reg?"Create your account":"Log in"}><div style={{maxWidth:400,margin:"0 auto"}}>{er&&<div style={{background:"rgba(255,100,100,.1)",border:"1px solid rgba(255,100,100,.3)",padding:"12px 16px",marginBottom:20,fontSize:13,color:"rgba(255,100,100,.8)",fontFamily:L}}>{er}</div>}{reg&&<><Inp l="Full name" v={nm} set={setNm} ph="Your name"/><Inp l="Phone" v={ph} set={setPh} ph="+234 800 000 0000"/></>}<Inp l="Email" v={em} set={setEm} ph="you@email.com" t="email"/><Inp l="Password" v={pw} set={setPw} ph="Min 6 characters" t="password"/><BP onClick={go} label={reg?"Create account":"Log in"} loading={ld} style={{width:"100%",marginTop:8}}/><p style={{textAlign:"center",marginTop:20,fontSize:14,color:"rgba(255,255,255,.4)",fontFamily:L}}>{reg?"Already registered?":"No account?"} <button onClick={()=>{setReg(!reg);setEr("");}} style={{background:"none",border:"none",color:"#fff",fontWeight:600,cursor:"pointer",fontFamily:L,textDecoration:"underline"}}>{reg?"Log in":"Register"}</button></p></div></PW>);};
const Inp=({l,v,set,ph,t="text"})=>(<div style={{marginBottom:16}}><label style={{display:"block",fontSize:12,color:"rgba(255,255,255,.35)",marginBottom:6,fontFamily:L}}>{l}</label><input type={t} value={v} onChange={e=>set(e.target.value)} placeholder={ph} style={{width:"100%",padding:"14px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.08)",color:"#fff",fontSize:15,outline:"none",boxSizing:"border-box",fontFamily:L}} onFocus={e=>e.target.style.borderColor="rgba(255,255,255,.4)"} onBlur={e=>e.target.style.borderColor="rgba(255,255,255,.08)"}/></div>);

const Portal=({user,setCP})=>{const[tab,setTab]=useState("dashboard");const[cd,setCD]=useState(null);const[ld,setLd]=useState(true);const[wk,setWk]=useState(0);
useEffect(()=>{if(!user)return;const unsub=onSnapshot(doc(db,"clients",user.uid),snap=>{if(snap.exists())setCD(snap.data());setLd(false);});return unsub;},[user]);
const lo=async()=>{await signOut(auth);setCP("home");};
if(ld)return<PW t="" st=""><div style={{textAlign:"center",paddingTop:40}}><Sp w/></div></PW>;
const tabs=["dashboard","workouts","progress","subscription","messages"];
return(<PW t="" st=""><div style={{maxWidth:800,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:32,flexWrap:"wrap",gap:16}}><div><h2 style={{fontSize:28,fontWeight:700,color:"#fff",margin:"0 0 4px",fontFamily:F}}>Welcome{cd?.name?`, ${cd.name.split(" ")[0]}`:""}</h2><p style={{color:"rgba(255,255,255,.35)",fontSize:14,margin:0,fontFamily:L}}>{user?.email}</p></div><button onClick={lo} style={{background:"none",border:"1px solid rgba(255,255,255,.15)",color:"rgba(255,255,255,.5)",padding:"8px 20px",fontSize:13,cursor:"pointer",fontFamily:L}}>Log out</button></div>
<div style={{display:"flex",gap:0,marginBottom:32,flexWrap:"wrap",overflowX:"auto"}}>{tabs.map(t=><button key={t} onClick={()=>setTab(t)} style={{padding:"10px 18px",background:tab===t?"#fff":"transparent",color:tab===t?"#000":"rgba(255,255,255,.4)",border:"1px solid",borderColor:tab===t?"#fff":"rgba(255,255,255,.08)",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:L,letterSpacing:1,textTransform:"uppercase",whiteSpace:"nowrap"}}>{t}</button>)}</div>
{tab==="dashboard"&&<PDash cd={cd} setTab={setTab}/>}
{tab==="workouts"&&<PWork cd={cd} user={user} wk={wk} setWk={setWk}/>}
{tab==="progress"&&<PProg cd={cd} user={user} setCD={setCD}/>}
{tab==="subscription"&&<PSub cd={cd}/>}
{tab==="messages"&&<PMsg cd={cd}/>}
</div></PW>);};

const StatBox=({label,value,sub,onClick})=>(<div onClick={onClick} style={{border:"1px solid rgba(255,255,255,.06)",padding:20,cursor:onClick?"pointer":"default",transition:"all .3s"}} onMouseEnter={e=>{if(onClick)e.currentTarget.style.borderColor="rgba(255,255,255,.3)";}} onMouseLeave={e=>{e.currentTarget.style.borderColor="rgba(255,255,255,.06)"}}><p style={{color:"rgba(255,255,255,.35)",fontSize:11,margin:"0 0 8px",fontFamily:L,letterSpacing:1}}>{label}</p><p style={{color:"#fff",fontSize:22,fontWeight:600,margin:0,fontFamily:L}}>{value}</p>{sub&&<p style={{color:"rgba(255,255,255,.25)",fontSize:12,margin:"4px 0 0",fontFamily:L}}>{sub}</p>}</div>);

const PDash=({cd,setTab})=>{const sub=cd?.subscription||{};const wk=cd?.workouts||cd?.program?.workouts||[];const logs=cd?.workoutLogs||[];const total=wk.length;const done=logs.length;const comp=total>0?Math.round((done/total)*100):0;
return(<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:16}}><StatBox label="PLAN" value={sub.plan||"None"} onClick={()=>setTab("subscription")}/><StatBox label="STATUS" value={sub.status==="active"?"Active":"Inactive"} onClick={()=>setTab("subscription")}/><StatBox label="COMPLIANCE" value={`${comp}%`} sub={`${done}/${total} workouts`} onClick={()=>setTab("workouts")}/><StatBox label="PROGRESS" value={`${cd?.progress?.weight?.length||0}`} sub="entries logged" onClick={()=>setTab("progress")}/><StatBox label="MESSAGES" value={`${cd?.messages?.length||0}`} onClick={()=>setTab("messages")}/></div>);};

const PWork=({cd,user,wk,setWk})=>{const workouts=cd?.program?.workouts||[];const logs=cd?.workoutLogs||[];const dates=weekDates(wk);const todayStr=today();
const dayWorkouts=date=>workouts.filter(w=>w.date===date);
const isLogged=(wid)=>logs.some(l=>l.workoutId===wid);
const logWorkout=async(workout)=>{const entry={workoutId:workout.id,date:today(),completedAt:new Date().toISOString(),exercises:workout.exercises?.map(e=>({name:e.name,sets:e.sets,reps:e.reps,weight:e.weight||""}))};const updated=[...logs,entry];await updateDoc(doc(db,"clients",user.uid),{workoutLogs:updated});};

return(<div>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:24}}><button onClick={()=>setWk(wk-1)} style={{background:"none",border:"1px solid rgba(255,255,255,.1)",color:"#fff",padding:"8px 16px",cursor:"pointer",fontFamily:L,fontSize:13}}>&#8592; Prev</button><span style={{color:"rgba(255,255,255,.5)",fontSize:14,fontFamily:L}}>{dates[0]} — {dates[6]}</span><button onClick={()=>setWk(wk+1)} style={{background:"none",border:"1px solid rgba(255,255,255,.1)",color:"#fff",padding:"8px 16px",cursor:"pointer",fontFamily:L,fontSize:13}}>Next &#8594;</button></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:8,marginBottom:32}}>
{dates.map(d=>{const ws=dayWorkouts(d);const isToday=d===todayStr;return(<div key={d} style={{border:"1px solid",borderColor:isToday?"rgba(255,255,255,.3)":"rgba(255,255,255,.06)",padding:12,minHeight:100,background:isToday?"rgba(255,255,255,.03)":"transparent"}}><p style={{color:isToday?"#fff":"rgba(255,255,255,.4)",fontSize:11,fontWeight:600,margin:"0 0 8px",fontFamily:L,textAlign:"center"}}>{dayName(d)}<br/><span style={{fontSize:16,fontWeight:600}}>{d.split("-")[2]}</span></p>{ws.length>0?ws.map((w,i)=><div key={i} style={{background:isLogged(w.id)?"rgba(255,255,255,.08)":"rgba(255,255,255,.03)",padding:6,marginBottom:4}}><p style={{color:"#fff",fontSize:11,fontWeight:600,margin:0,fontFamily:L}}>{w.name}</p>{w.exercises?.map((e,j)=><p key={j} style={{color:"rgba(255,255,255,.3)",fontSize:10,margin:"2px 0 0",fontFamily:L}}>{e.name}: {e.sets}x{e.reps}</p>)}{!isLogged(w.id)&&d<=todayStr&&<button onClick={()=>logWorkout(w)} style={{background:"#fff",color:"#000",border:"none",fontSize:10,fontWeight:600,padding:"4px 8px",marginTop:4,cursor:"pointer",fontFamily:L,width:"100%"}}>Done</button>}</div>):<p style={{color:"rgba(255,255,255,.15)",fontSize:11,textAlign:"center",fontFamily:L}}>Rest</p>}</div>);})}
</div>
<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24}}><p style={{color:"rgba(255,255,255,.35)",fontSize:12,margin:"0 0 8px",fontFamily:L,letterSpacing:1}}>CURRENT PROGRAM</p><p style={{color:"#fff",fontSize:15,margin:0,fontFamily:L,lineHeight:1.7}}>{cd?.program?.current||"No program assigned yet. Your trainer will set this up."}</p></div>
</div>);};

const PProg=({cd,user,setCD})=>{const[wt,setWt]=useState("");const[nt,setNt]=useState("");const[sv,setSv]=useState(false);const weights=cd?.progress?.weight||[];
const[mType,setMT]=useState("chest");const[mVal,setMV]=useState("");const measurements=cd?.progress?.measurements||[];
const logW=async()=>{if(!wt)return;setSv(true);const e={value:parseFloat(wt),note:nt,date:today()};const u=[...weights,e];await updateDoc(doc(db,"clients",user.uid),{"progress.weight":u});setCD({...cd,progress:{...cd.progress,weight:u}});setWt("");setNt("");setSv(false);};
const logM=async()=>{if(!mVal)return;setSv(true);const e={type:mType,value:parseFloat(mVal),date:today()};const u=[...measurements,e];await updateDoc(doc(db,"clients",user.uid),{"progress.measurements":u});setCD({...cd,progress:{...cd.progress,measurements:u}});setMV("");setSv(false);};
return(<div>
<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24,marginBottom:20}}><p style={{color:"rgba(255,255,255,.35)",fontSize:12,margin:"0 0 16px",fontFamily:L,letterSpacing:1}}>LOG WEIGHT</p><div style={{display:"flex",gap:12,marginBottom:12,flexWrap:"wrap"}}><input value={wt} onChange={e=>setWt(e.target.value)} placeholder="Weight (kg)" type="number" style={{flex:1,minWidth:120,padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.08)",color:"#fff",fontSize:14,outline:"none",fontFamily:L}}/><input value={nt} onChange={e=>setNt(e.target.value)} placeholder="Notes" style={{flex:2,minWidth:180,padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.08)",color:"#fff",fontSize:14,outline:"none",fontFamily:L}}/></div><BP onClick={logW} label="Log weight" loading={sv} style={{padding:"12px 32px"}}/></div>

<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24,marginBottom:20}}><p style={{color:"rgba(255,255,255,.35)",fontSize:12,margin:"0 0 16px",fontFamily:L,letterSpacing:1}}>LOG MEASUREMENTS</p><div style={{display:"flex",gap:12,marginBottom:12,flexWrap:"wrap"}}><select value={mType} onChange={e=>setMT(e.target.value)} style={{padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.08)",color:"#fff",fontSize:14,fontFamily:L,outline:"none"}}>{["chest","waist","hips","arms","thighs","shoulders"].map(x=><option key={x} value={x} style={{background:"#111"}}>{x.charAt(0).toUpperCase()+x.slice(1)}</option>)}</select><input value={mVal} onChange={e=>setMV(e.target.value)} placeholder="cm" type="number" style={{flex:1,minWidth:100,padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.08)",color:"#fff",fontSize:14,outline:"none",fontFamily:L}}/></div><BP onClick={logM} label="Log measurement" loading={sv} style={{padding:"12px 32px"}}/></div>

<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24,marginBottom:20}}><p style={{color:"rgba(255,255,255,.35)",fontSize:12,margin:"0 0 16px",fontFamily:L,letterSpacing:1}}>WEIGHT HISTORY</p>{weights.length>0?[...weights].reverse().map((w,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:"1px solid rgba(255,255,255,.04)"}}><div><span style={{color:"#fff",fontSize:16,fontWeight:600,fontFamily:L}}>{w.value}kg</span>{w.note&&<span style={{color:"rgba(255,255,255,.3)",fontSize:13,marginLeft:12,fontFamily:L}}>{w.note}</span>}</div><span style={{color:"rgba(255,255,255,.3)",fontSize:13,fontFamily:L}}>{w.date}</span></div>):<p style={{color:"rgba(255,255,255,.3)",fontSize:14,fontFamily:L}}>No entries yet.</p>}</div>

<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24}}><p style={{color:"rgba(255,255,255,.35)",fontSize:12,margin:"0 0 16px",fontFamily:L,letterSpacing:1}}>MEASUREMENT HISTORY</p>{measurements.length>0?[...measurements].reverse().map((m,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:"1px solid rgba(255,255,255,.04)"}}><div><span style={{color:"#fff",fontSize:14,fontWeight:600,fontFamily:L}}>{m.type}</span><span style={{color:"rgba(255,255,255,.5)",fontSize:14,marginLeft:12,fontFamily:L}}>{m.value}cm</span></div><span style={{color:"rgba(255,255,255,.3)",fontSize:13,fontFamily:L}}>{m.date}</span></div>):<p style={{color:"rgba(255,255,255,.3)",fontSize:14,fontFamily:L}}>No measurements yet.</p>}</div>
</div>);};

const PSub=({cd})=>{const sub=cd?.subscription||{};const act=sub.status==="active";return(<div><div style={{border:"1px solid rgba(255,255,255,.06)",padding:24,marginBottom:20}}><p style={{color:"rgba(255,255,255,.35)",fontSize:12,margin:"0 0 16px",fontFamily:L,letterSpacing:1}}>YOUR SUBSCRIPTION</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20}}><div><p style={{color:"rgba(255,255,255,.35)",fontSize:12,margin:"0 0 4px",fontFamily:L}}>Plan</p><p style={{color:"#fff",fontSize:18,fontWeight:600,margin:0,fontFamily:L}}>{sub.plan||"None"}</p></div><div><p style={{color:"rgba(255,255,255,.35)",fontSize:12,margin:"0 0 4px",fontFamily:L}}>Status</p><p style={{color:act?"#4ade80":"rgba(255,255,255,.5)",fontSize:18,fontWeight:600,margin:0,fontFamily:L}}>{act?"Active":"Inactive"}</p></div>{sub.startDate&&<div><p style={{color:"rgba(255,255,255,.35)",fontSize:12,margin:"0 0 4px",fontFamily:L}}>Started</p><p style={{color:"#fff",fontSize:14,margin:0,fontFamily:L}}>{sub.startDate}</p></div>}{sub.endDate&&<div><p style={{color:"rgba(255,255,255,.35)",fontSize:12,margin:"0 0 4px",fontFamily:L}}>Expires</p><p style={{color:"#fff",fontSize:14,margin:0,fontFamily:L}}>{sub.endDate}</p></div>}</div></div><div style={{display:"flex",gap:16,flexWrap:"wrap"}}>{act?<BP onClick={()=>{window.location.href=`https://wa.me/${WN}?text=${encodeURIComponent("Hi! I'd like to renew my "+sub.plan+" membership.")}`;}} label="Renew membership" style={{flex:1}}/>:<BP onClick={()=>{window.location.href=`https://wa.me/${WN}?text=${encodeURIComponent("Hi! I'd like to start a membership.")}`;}} label="Get a membership" style={{flex:1}}/>}<BO onClick={()=>{window.location.href=`https://wa.me/${WN}?text=${encodeURIComponent("Hi, question about my subscription.")}`;}} label="Contact support" style={{flex:1}}/></div></div>);};

const PMsg=({cd})=>{const msgs=cd?.messages||[];return(<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24}}><p style={{color:"rgba(255,255,255,.35)",fontSize:12,margin:"0 0 16px",fontFamily:L,letterSpacing:1}}>MESSAGES FROM YOUR TRAINER</p>{msgs.length>0?msgs.map((m,i)=><div key={i} style={{padding:16,marginBottom:12,background:"rgba(255,255,255,.03)",borderLeft:"3px solid rgba(255,255,255,.2)"}}><p style={{color:"#fff",fontSize:14,margin:"0 0 8px",fontFamily:L,lineHeight:1.6}}>{m.text}</p><p style={{color:"rgba(255,255,255,.25)",fontSize:12,margin:0,fontFamily:L}}>{m.date} {m.from&&`— ${m.from}`}</p></div>):<p style={{color:"rgba(255,255,255,.3)",fontSize:14,fontFamily:L}}>No messages yet. Your trainer will post updates here.</p>}</div>);};

const PW=({t,st,children})=>(<div style={{minHeight:"100vh",paddingTop:100,paddingBottom:60,paddingLeft:24,paddingRight:24,background:"#000"}}><div style={{textAlign:"center",marginBottom:48}}>{t&&<AI><h2 style={{fontSize:"clamp(28px,5vw,40px)",fontWeight:700,color:"#fff",margin:"0 0 8px",fontFamily:F}}>{t}</h2></AI>}{st&&<AI delay={.1}><p style={{fontSize:15,color:"rgba(255,255,255,.3)",margin:0,fontFamily:L}}>{st}</p></AI>}</div>{children}</div>);

/* ========== COACH DASHBOARD ========== */
const CoachDash=({user,setCP})=>{
const[clients,setClients]=useState([]);const[ld,setLd]=useState(true);const[sel,setSel]=useState(null);const[cData,setCData]=useState(null);const[view,setView]=useState("clients");const[exLib,setExLib]=useState([]);const[toast,showToast]=useToast();
useEffect(()=>{if(!user||!isAdmin(user.email)){setCP("home");return;}const fetchAll=async()=>{const snap=await getDocs(collection(db,"clients"));const arr=[];snap.forEach(d=>arr.push({id:d.id,...d.data()}));setClients(arr);const exSnap=await getDocs(collection(db,"exerciseLibrary"));const exArr=[];exSnap.forEach(d=>exArr.push({id:d.id,...d.data()}));setExLib(exArr);setLd(false);};fetchAll();},[user]);

const selectClient=async(id)=>{const snap=await getDoc(doc(db,"clients",id));if(snap.exists()){setCData({id,...snap.data()});setSel(id);}};
const refreshClient=async()=>{if(!sel)return;const snap=await getDoc(doc(db,"clients",sel));if(snap.exists())setCData({id:sel,...snap.data()});};
const refreshExLib=async()=>{const exSnap=await getDocs(collection(db,"exerciseLibrary"));const exArr=[];exSnap.forEach(d=>exArr.push({id:d.id,...d.data()}));setExLib(exArr);};

if(ld)return<PW t="Coach dashboard" st=""><div style={{textAlign:"center",paddingTop:40}}><Sp w/></div></PW>;
if(sel&&cData)return<><ClientManager c={cData} back={()=>{setSel(null);setCData(null);}} refresh={refreshClient} exLib={exLib} showToast={showToast}/><Toast {...toast}/></>;
return(<PW t="Coach dashboard" st=""><div style={{maxWidth:700,margin:"0 auto"}}>
<div style={{display:"flex",gap:0,marginBottom:32}}><button onClick={()=>setView("clients")} style={{padding:"12px 28px",background:view==="clients"?"#fff":"transparent",color:view==="clients"?"#000":"rgba(255,255,255,.4)",border:"1px solid",borderColor:view==="clients"?"#fff":"rgba(255,255,255,.1)",fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:L,letterSpacing:1}}>CLIENTS ({clients.length})</button><button onClick={()=>setView("exercises")} style={{padding:"12px 28px",background:view==="exercises"?"#fff":"transparent",color:view==="exercises"?"#000":"rgba(255,255,255,.4)",border:"1px solid",borderColor:view==="exercises"?"#fff":"rgba(255,255,255,.1)",fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:L,letterSpacing:1}}>EXERCISE LIBRARY ({exLib.length})</button></div>

{view==="clients"&&clients.map(c=><div key={c.id} onClick={()=>selectClient(c.id)} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"16px 20px",border:"1px solid rgba(255,255,255,.06)",marginBottom:8,cursor:"pointer",transition:"all .3s"}} onMouseEnter={e=>e.currentTarget.style.borderColor="rgba(255,255,255,.3)"} onMouseLeave={e=>e.currentTarget.style.borderColor="rgba(255,255,255,.06)"}><div><p style={{color:"#fff",fontSize:16,fontWeight:600,margin:"0 0 4px",fontFamily:L}}>{c.name||"No name"}</p><p style={{color:"rgba(255,255,255,.35)",fontSize:13,margin:0,fontFamily:L}}>{c.email}</p></div><div style={{textAlign:"right"}}><p style={{color:statusColor(c.subscription?.status),fontSize:13,fontWeight:600,margin:"0 0 4px",fontFamily:L}}>{c.subscription?.status?c.subscription.status.charAt(0).toUpperCase()+c.subscription.status.slice(1):"Inactive"}</p><p style={{color:"rgba(255,255,255,.25)",fontSize:12,margin:0,fontFamily:L}}>{c.subscription?.plan||"No plan"}</p></div></div>)}

{view==="exercises"&&<ExerciseLibrary exLib={exLib} refresh={refreshExLib} showToast={showToast}/>}
</div><Toast {...toast}/></PW>);
};

const ExerciseLibrary=({exLib,refresh,showToast})=>{
const[search,setSearch]=useState("");const[nm,setNm]=useState("");const[cat,setCat]=useState("Strength");const[notes,setNotes]=useState("");const[sv,setSv]=useState(false);
const cats=["Strength","Cardio","Core","Flexibility","HIIT","Plyometrics","Warm-up","Cool-down"];
const filtered=exLib.filter(e=>e.name.toLowerCase().includes(search.toLowerCase())||e.category?.toLowerCase().includes(search.toLowerCase()));
const addEx=async()=>{if(!nm.trim())return;setSv(true);await addDoc(collection(db,"exerciseLibrary"),{name:nm,category:cat,notes:notes,createdAt:today()});setNm("");setNotes("");setSv(false);await refresh();showToast("Exercise added");};
return(<div>
<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24,marginBottom:20}}>
<p style={{color:"#fff",fontSize:14,margin:"0 0 16px",fontFamily:L,fontWeight:600,letterSpacing:1}}>ADD NEW EXERCISE</p>
<div style={{display:"flex",gap:12,marginBottom:12,flexWrap:"wrap"}}><input value={nm} onChange={e=>setNm(e.target.value)} placeholder="Exercise name" style={{flex:2,minWidth:180,padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.08)",color:"#fff",fontSize:14,outline:"none",fontFamily:L}}/><select value={cat} onChange={e=>setCat(e.target.value)} style={{flex:1,minWidth:120,padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.08)",color:"#fff",fontSize:14,fontFamily:L,outline:"none"}}>{cats.map(c=><option key={c} value={c} style={{background:"#111"}}>{c}</option>)}</select></div>
<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Notes (optional, e.g. cues or tips)" style={{width:"100%",padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.08)",color:"#fff",fontSize:14,outline:"none",fontFamily:L,boxSizing:"border-box",marginBottom:12}}/>
<BP onClick={addEx} label="Add to library" loading={sv} style={{padding:"12px 32px"}}/>
</div>

<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24}}>
<p style={{color:"#fff",fontSize:14,margin:"0 0 16px",fontFamily:L,fontWeight:600,letterSpacing:1}}>EXERCISE LOG</p>
<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search exercises..." style={{width:"100%",padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.08)",color:"#fff",fontSize:14,outline:"none",fontFamily:L,boxSizing:"border-box",marginBottom:16}}/>
{filtered.length>0?filtered.sort((a,b)=>a.name.localeCompare(b.name)).map(e=><div key={e.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px 0",borderBottom:"1px solid rgba(255,255,255,.04)"}}><div><p style={{color:"#fff",fontSize:15,fontWeight:600,margin:"0 0 2px",fontFamily:L}}>{e.name}</p><p style={{color:"rgba(255,255,255,.35)",fontSize:12,margin:0,fontFamily:L}}>{e.category}{e.notes?` — ${e.notes}`:""}</p></div><span style={{color:"rgba(255,255,255,.2)",fontSize:12,fontFamily:L}}>{e.category}</span></div>):<p style={{color:"rgba(255,255,255,.3)",fontSize:14,fontFamily:L}}>No exercises found. Add some above.</p>}
</div>
</div>);};

const ClientManager=({c,back,refresh,exLib,showToast})=>{
const[tab,setTab]=useState("overview");
const tabs=["overview","workouts","subscription","messages","progress"];
return(<PW t="" st=""><div style={{maxWidth:700,margin:"0 auto"}}>
<button onClick={back} style={{background:"none",border:"none",color:"rgba(255,255,255,.5)",fontSize:14,cursor:"pointer",fontFamily:L,marginBottom:20}}>&#8592; Back to clients</button>
<div style={{marginBottom:24}}><h2 style={{fontSize:24,fontWeight:700,color:"#fff",margin:"0 0 4px",fontFamily:F}}>{c.name}</h2><p style={{color:"rgba(255,255,255,.35)",fontSize:14,margin:"0 0 2px",fontFamily:L}}>{c.email}</p><p style={{color:"rgba(255,255,255,.25)",fontSize:13,margin:0,fontFamily:L}}>{c.phone}</p></div>
<div style={{display:"flex",gap:0,marginBottom:32,flexWrap:"wrap",overflowX:"auto"}}>{tabs.map(t=><button key={t} onClick={()=>setTab(t)} style={{padding:"10px 16px",background:tab===t?"#fff":"transparent",color:tab===t?"#000":"rgba(255,255,255,.4)",border:"1px solid",borderColor:tab===t?"#fff":"rgba(255,255,255,.08)",fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:L,letterSpacing:1,textTransform:"uppercase",whiteSpace:"nowrap"}}>{t}</button>)}</div>
{tab==="overview"&&<CoachOverview c={c}/>}
{tab==="workouts"&&<CoachWorkouts c={c} refresh={refresh} exLib={exLib} showToast={showToast}/>}
{tab==="subscription"&&<CoachSub c={c} refresh={refresh} showToast={showToast}/>}
{tab==="messages"&&<CoachMsg c={c} refresh={refresh} showToast={showToast}/>}
{tab==="progress"&&<CoachProgress c={c}/>}
</div></PW>);
};

const CoachOverview=({c})=>{const sub=c.subscription||{};const wk=c.program?.workouts||[];const logs=c.workoutLogs||[];const weights=c.progress?.weight||[];return(<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12}}><StatBox label="PLAN" value={sub.plan||"None"}/><StatBox label="STATUS" value={sub.status?sub.status.charAt(0).toUpperCase()+sub.status.slice(1):"Inactive"} sub={<span style={{color:statusColor(sub.status),fontSize:12}}>&#9679; {sub.status||"inactive"}</span>}/><StatBox label="WORKOUTS" value={`${wk.length} assigned`}/><StatBox label="COMPLETED" value={`${logs.length}`}/><StatBox label="WEIGHT LOGS" value={`${weights.length}`}/><StatBox label="JOINED" value={c.createdAt?.split("T")[0]||"—"}/></div>);};

const CoachWorkouts=({c,refresh,exLib,showToast})=>{
const[nm,setNm]=useState("");const[dt,setDt]=useState(today());const[exs,setExs]=useState([{name:"",sets:"3",reps:"10",weight:""}]);const[sv,setSv]=useState(false);const[prog,setProg]=useState(c.program?.current||"");const[mode,setMode]=useState("manual");
const addEx=()=>setExs([...exs,{name:"",sets:"3",reps:"10",weight:""}]);
const updEx=(i,k,v)=>{const u=[...exs];u[i][k]=v;setExs(u);};
const rmEx=(i)=>setExs(exs.filter((_,j)=>j!==i));
const addFromLib=(exName)=>{setExs([...exs,{name:exName,sets:"3",reps:"10",weight:""}]);};
const save=async()=>{if(!nm.trim()){showToast("Enter workout name");return;}if(exs.filter(e=>e.name.trim()).length===0){showToast("Add at least 1 exercise");return;}setSv(true);const wk=c.program?.workouts||[];const nw={id:`w${Date.now()}`,name:nm,date:dt,exercises:exs.filter(e=>e.name.trim())};const updated=[...wk,nw];await updateDoc(doc(db,"clients",c.id),{"program.workouts":updated,"program.current":prog||c.program?.current||""});setNm("");setExs([{name:"",sets:"3",reps:"10",weight:""}]);setSv(false);await refresh();showToast("Workout saved");};
const saveProg=async()=>{await updateDoc(doc(db,"clients",c.id),{"program.current":prog});await refresh();showToast("Program description saved");};
const delW=async(wid)=>{const wk=(c.program?.workouts||[]).filter(w=>w.id!==wid);await updateDoc(doc(db,"clients",c.id),{"program.workouts":wk});await refresh();showToast("Workout deleted");};
const existing=c.program?.workouts||[];
return(<div>
<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24,marginBottom:20}}>
<p style={{color:"#fff",fontSize:14,margin:"0 0 12px",fontFamily:L,fontWeight:600,letterSpacing:1}}>PROGRAM DESCRIPTION</p>
<textarea value={prog} onChange={e=>setProg(e.target.value)} rows={3} style={{width:"100%",padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.08)",color:"#fff",fontSize:14,outline:"none",fontFamily:L,boxSizing:"border-box",resize:"vertical"}} placeholder="e.g. 8-week muscle gain program"/>
<BP onClick={saveProg} label="Save description" style={{padding:"10px 24px",marginTop:12}}/>
</div>

<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24,marginBottom:20}}>
<p style={{color:"#fff",fontSize:14,margin:"0 0 16px",fontFamily:L,fontWeight:600,letterSpacing:1}}>ADD WORKOUT</p>
<div style={{display:"flex",gap:12,marginBottom:16,flexWrap:"wrap"}}><input value={nm} onChange={e=>setNm(e.target.value)} placeholder="Workout name (e.g. Upper Body)" style={{flex:2,minWidth:180,padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.15)",color:"#fff",fontSize:14,outline:"none",fontFamily:L}}/><input type="date" value={dt} onChange={e=>setDt(e.target.value)} style={{flex:1,minWidth:140,padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.15)",color:"#fff",fontSize:14,outline:"none",fontFamily:L}}/></div>

<div style={{display:"flex",gap:0,marginBottom:12}}><button onClick={()=>setMode("manual")} style={{padding:"8px 16px",background:mode==="manual"?"#fff":"transparent",color:mode==="manual"?"#000":"rgba(255,255,255,.4)",border:"1px solid",borderColor:mode==="manual"?"#fff":"rgba(255,255,255,.1)",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:L}}>TYPE MANUALLY</button><button onClick={()=>setMode("library")} style={{padding:"8px 16px",background:mode==="library"?"#fff":"transparent",color:mode==="library"?"#000":"rgba(255,255,255,.4)",border:"1px solid",borderColor:mode==="library"?"#fff":"rgba(255,255,255,.1)",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:L}}>FROM LIBRARY</button></div>

{mode==="library"&&<div style={{marginBottom:16,border:"1px solid rgba(255,255,255,.1)",padding:16,maxHeight:200,overflowY:"auto"}}>{exLib.length>0?exLib.sort((a,b)=>a.name.localeCompare(b.name)).map(e=><div key={e.id} onClick={()=>addFromLib(e.name)} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 0",borderBottom:"1px solid rgba(255,255,255,.04)",cursor:"pointer",transition:"all .2s"}} onMouseEnter={ev=>ev.currentTarget.style.background="rgba(255,255,255,.05)"} onMouseLeave={ev=>ev.currentTarget.style.background="transparent"}><span style={{color:"#fff",fontSize:14,fontWeight:500,fontFamily:L}}>{e.name}</span><span style={{color:"rgba(255,255,255,.3)",fontSize:12,fontFamily:L}}>{e.category} +</span></div>):<p style={{color:"rgba(255,255,255,.3)",fontSize:13,fontFamily:L}}>No exercises in library. Add some in the Exercise Library tab.</p>}</div>}

<p style={{color:"#fff",fontSize:12,margin:"0 0 8px",fontFamily:L,fontWeight:600,letterSpacing:1}}>EXERCISES ({exs.filter(e=>e.name.trim()).length})</p>
{exs.map((e,i)=><div key={i} style={{display:"flex",gap:8,marginBottom:8,flexWrap:"wrap",alignItems:"center"}}><input value={e.name} onChange={ev=>updEx(i,"name",ev.target.value)} placeholder="Exercise name" style={{flex:3,minWidth:140,padding:"10px 12px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.15)",color:"#fff",fontSize:14,outline:"none",fontFamily:L}}/><input value={e.sets} onChange={ev=>updEx(i,"sets",ev.target.value)} placeholder="Sets" style={{width:55,padding:"10px 8px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.15)",color:"#fff",fontSize:14,outline:"none",fontFamily:L,textAlign:"center"}}/><span style={{color:"rgba(255,255,255,.3)",fontSize:12}}>x</span><input value={e.reps} onChange={ev=>updEx(i,"reps",ev.target.value)} placeholder="Reps" style={{width:55,padding:"10px 8px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.15)",color:"#fff",fontSize:14,outline:"none",fontFamily:L,textAlign:"center"}}/><input value={e.weight||""} onChange={ev=>updEx(i,"weight",ev.target.value)} placeholder="kg" style={{width:55,padding:"10px 8px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.15)",color:"#fff",fontSize:14,outline:"none",fontFamily:L,textAlign:"center"}}/>{exs.length>1&&<button onClick={()=>rmEx(i)} style={{background:"none",border:"none",color:"rgba(255,255,255,.4)",cursor:"pointer",fontSize:18,padding:4}}>&#10005;</button>}</div>)}
<button onClick={addEx} style={{background:"rgba(255,255,255,.05)",border:"1px solid rgba(255,255,255,.15)",color:"#fff",padding:"10px 20px",fontSize:13,cursor:"pointer",fontFamily:L,marginBottom:16,fontWeight:500}}>+ Add exercise</button>
<div><BP onClick={save} label="Save workout" loading={sv} style={{padding:"12px 32px"}}/></div>
</div>

<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24}}>
<p style={{color:"#fff",fontSize:14,margin:"0 0 16px",fontFamily:L,fontWeight:600,letterSpacing:1}}>ASSIGNED WORKOUTS ({existing.length})</p>
{existing.length>0?[...existing].sort((a,b)=>a.date>b.date?1:-1).map(w=><div key={w.id} style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",padding:"14px 0",borderBottom:"1px solid rgba(255,255,255,.06)"}}><div><p style={{color:"#fff",fontSize:15,fontWeight:600,margin:"0 0 4px",fontFamily:L}}>{w.name}</p><p style={{color:"rgba(255,255,255,.5)",fontSize:13,margin:"0 0 6px",fontFamily:L}}>{w.date} ({dayName(w.date)})</p>{w.exercises?.map((e,j)=><p key={j} style={{color:"rgba(255,255,255,.6)",fontSize:13,margin:"2px 0",fontFamily:L}}>&#8226; {e.name}: {e.sets}x{e.reps}{e.weight?` @ ${e.weight}kg`:""}</p>)}</div><button onClick={()=>delW(w.id)} style={{background:"none",border:"1px solid rgba(255,255,255,.1)",color:"rgba(255,255,255,.4)",cursor:"pointer",fontSize:12,padding:"6px 12px",fontFamily:L,whiteSpace:"nowrap"}}>Delete</button></div>):<p style={{color:"rgba(255,255,255,.3)",fontSize:14,fontFamily:L}}>No workouts assigned yet.</p>}
</div>
</div>);};

const CoachSub=({c,refresh,showToast})=>{
const sub=c.subscription||{};const[plan,setPlan]=useState(sub.plan||"None");const[status,setStatus]=useState(sub.status||"inactive");const[sd,setSD]=useState(sub.startDate||"");const[ed,setED]=useState(sub.endDate||"");const[sv,setSv]=useState(false);
const save=async()=>{setSv(true);await updateDoc(doc(db,"clients",c.id),{subscription:{plan,status,startDate:sd||null,endDate:ed||null}});setSv(false);await refresh();showToast("Subscription saved");};
const plans=["None","3-Session Starter Pack","1:1 Trainer + Equipment","1:1 Trainer Only (Home)","1:1 Trainer Only (Gym)","Virtual Session","2x/week (Trainer+Equip)","3x/week (Trainer+Equip)","5x/week (Trainer+Equip)","2x/week (Trainer Only)","3x/week (Trainer Only)","5x/week (Trainer Only)"];
return(<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24}}>
<p style={{color:"#fff",fontSize:14,margin:"0 0 16px",fontFamily:L,fontWeight:600,letterSpacing:1}}>MANAGE SUBSCRIPTION</p>
<div style={{display:"inline-flex",alignItems:"center",gap:8,marginBottom:20,padding:"8px 16px",border:`1px solid ${statusColor(status)}`,background:"rgba(0,0,0,.3)"}}><span style={{width:8,height:8,borderRadius:"50%",background:statusColor(status),display:"inline-block"}}></span><span style={{color:statusColor(status),fontSize:13,fontWeight:600,fontFamily:L}}>{status?status.charAt(0).toUpperCase()+status.slice(1):"Inactive"}</span></div>
<div style={{marginBottom:16}}><label style={{display:"block",fontSize:12,color:"#fff",marginBottom:6,fontFamily:L,fontWeight:500}}>Plan</label><select value={plan} onChange={e=>setPlan(e.target.value)} style={{width:"100%",padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.15)",color:"#fff",fontSize:14,fontFamily:L,outline:"none"}}>{plans.map(p=><option key={p} value={p} style={{background:"#111"}}>{p}</option>)}</select></div>
<div style={{marginBottom:16}}><label style={{display:"block",fontSize:12,color:"#fff",marginBottom:6,fontFamily:L,fontWeight:500}}>Status</label><select value={status} onChange={e=>setStatus(e.target.value)} style={{width:"100%",padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.15)",color:"#fff",fontSize:14,fontFamily:L,outline:"none"}}><option value="active" style={{background:"#111"}}>Active</option><option value="inactive" style={{background:"#111"}}>Inactive</option><option value="paused" style={{background:"#111"}}>Paused</option><option value="expired" style={{background:"#111"}}>Expired</option><option value="cancelled" style={{background:"#111"}}>Cancelled</option></select></div>
<div style={{display:"flex",gap:12,marginBottom:20,flexWrap:"wrap"}}><div style={{flex:1,minWidth:140}}><label style={{display:"block",fontSize:12,color:"#fff",marginBottom:6,fontFamily:L,fontWeight:500}}>Start date</label><input type="date" value={sd} onChange={e=>setSD(e.target.value)} style={{width:"100%",padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.15)",color:"#fff",fontSize:14,outline:"none",fontFamily:L,boxSizing:"border-box"}}/></div><div style={{flex:1,minWidth:140}}><label style={{display:"block",fontSize:12,color:"#fff",marginBottom:6,fontFamily:L,fontWeight:500}}>End date</label><input type="date" value={ed} onChange={e=>setED(e.target.value)} style={{width:"100%",padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.15)",color:"#fff",fontSize:14,outline:"none",fontFamily:L,boxSizing:"border-box"}}/></div></div>
<BP onClick={save} label="Save subscription" loading={sv} style={{padding:"12px 32px"}}/>
</div>);};

const CoachMsg=({c,refresh,showToast})=>{
const[txt,setTxt]=useState("");const[sv,setSv]=useState(false);
const send=async()=>{if(!txt.trim()){showToast("Type a message first");return;}setSv(true);const msgs=c.messages||[];const nw={text:txt,date:today(),from:"Off-Szn Coach"};await updateDoc(doc(db,"clients",c.id),{messages:[...msgs,nw]});setTxt("");setSv(false);await refresh();showToast("Message sent");};
const msgs=c.messages||[];
return(<div>
<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24,marginBottom:20}}>
<p style={{color:"#fff",fontSize:14,margin:"0 0 12px",fontFamily:L,fontWeight:600,letterSpacing:1}}>SEND MESSAGE</p>
<textarea value={txt} onChange={e=>setTxt(e.target.value)} rows={3} placeholder="Type a message to this client..." style={{width:"100%",padding:"12px 16px",background:"rgba(255,255,255,.03)",border:"1px solid rgba(255,255,255,.15)",color:"#fff",fontSize:14,outline:"none",fontFamily:L,boxSizing:"border-box",resize:"vertical",marginBottom:12}}/>
<BP onClick={send} label="Send message" loading={sv} style={{padding:"12px 32px"}}/>
</div>
<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24}}>
<p style={{color:"#fff",fontSize:14,margin:"0 0 16px",fontFamily:L,fontWeight:600,letterSpacing:1}}>MESSAGE HISTORY ({msgs.length})</p>
{msgs.length>0?[...msgs].reverse().map((m,i)=><div key={i} style={{padding:16,marginBottom:8,background:"rgba(255,255,255,.03)",borderLeft:"3px solid rgba(255,255,255,.2)"}}><p style={{color:"#fff",fontSize:14,margin:"0 0 6px",fontFamily:L,lineHeight:1.6}}>{m.text}</p><p style={{color:"rgba(255,255,255,.35)",fontSize:12,margin:0,fontFamily:L}}>{m.date} — {m.from||"Coach"}</p></div>):<p style={{color:"rgba(255,255,255,.3)",fontSize:14,fontFamily:L}}>No messages sent yet.</p>}
</div>
</div>);};

const CoachProgress=({c})=>{
const weights=c.progress?.weight||[];const measurements=c.progress?.measurements||[];
return(<div>
<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24,marginBottom:20}}>
<p style={{color:"#fff",fontSize:14,margin:"0 0 16px",fontFamily:L,fontWeight:600,letterSpacing:1}}>WEIGHT HISTORY ({weights.length} entries)</p>
{weights.length>0?[...weights].reverse().map((w,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:"1px solid rgba(255,255,255,.04)"}}><div><span style={{color:"#fff",fontSize:16,fontWeight:600,fontFamily:L}}>{w.value}kg</span>{w.note&&<span style={{color:"rgba(255,255,255,.5)",fontSize:13,marginLeft:12,fontFamily:L}}>{w.note}</span>}</div><span style={{color:"rgba(255,255,255,.4)",fontSize:13,fontFamily:L}}>{w.date}</span></div>):<p style={{color:"rgba(255,255,255,.3)",fontSize:14,fontFamily:L}}>No weight entries.</p>}
</div>
<div style={{border:"1px solid rgba(255,255,255,.06)",padding:24}}>
<p style={{color:"#fff",fontSize:14,margin:"0 0 16px",fontFamily:L,fontWeight:600,letterSpacing:1}}>MEASUREMENTS ({measurements.length} entries)</p>
{measurements.length>0?[...measurements].reverse().map((m,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:"1px solid rgba(255,255,255,.04)"}}><div><span style={{color:"#fff",fontSize:14,fontWeight:600,fontFamily:L}}>{m.type}</span><span style={{color:"rgba(255,255,255,.6)",fontSize:14,marginLeft:12,fontFamily:L}}>{m.value}cm</span></div><span style={{color:"rgba(255,255,255,.4)",fontSize:13,fontFamily:L}}>{m.date}</span></div>):<p style={{color:"rgba(255,255,255,.3)",fontSize:14,fontFamily:L}}>No measurements.</p>}
</div>
</div>);};

export default function App(){const[mo,setMO]=useState(false);const[co,setCO]=useState(false);const[cart,setCart]=useState([]);const[cp,setCP]=useState("home");const[user,setUser]=useState(null);
useEffect(()=>{document.title="Off-Szn Mobile Gym — We Pull Up. You Level Up.";},[]);
useEffect(()=>{window.scrollTo({top:0,behavior:"smooth"});},[cp]);
useEffect(()=>{const u=onAuthStateChanged(auth,u=>setUser(u));return u;},[]);
const rp=()=>{switch(cp){case"memberships":return<MP/>;case"store":return<SP cart={cart} setCart={setCart}/>;case"signup":return<SUP setCP={setCP}/>;case"consultation":return<CSP/>;case"training":return<TP/>;case"virtual":return<VP setCP={setCP}/>;case"contact":return<CTP/>;case"login":return<LP setCP={setCP}/>;case"portal":return user?<Portal user={user} setCP={setCP}/>:<LP setCP={setCP}/>;case"coach":return user&&isAdmin(user.email)?<CoachDash user={user} setCP={setCP}/>:<LP setCP={setCP}/>;default:return(<><Hero/><HIW/><IO/><RS/><Ftr setCP={setCP}/></>);}};
return(<div style={{background:"#000",minHeight:"100vh",fontFamily:L,color:"#fff",overflowX:"hidden"}}><div style={{position:"fixed",top:0,left:0,width:"100%",height:64,background:"transparent",display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 24px",zIndex:1000}}><button onClick={()=>{setMO(!mo);setCO(false);}} style={{background:"none",border:"none",cursor:"pointer",padding:8,display:"flex",flexDirection:"column",gap:5}}><span style={{display:"block",width:24,height:2,background:"#fff",transition:"all .4s",transform:mo?"rotate(45deg) translate(5px,5px)":"none"}}/><span style={{display:"block",width:24,height:2,background:"#fff",transition:"all .4s",opacity:mo?0:1}}/><span style={{display:"block",width:24,height:2,background:"#fff",transition:"all .4s",transform:mo?"rotate(-45deg) translate(5px,-5px)":"none"}}/></button><span onClick={()=>{setCP("home");setMO(false);setCO(false);}} style={{cursor:"pointer"}}><LogoS/></span><CartB count={cart.reduce((s,i)=>s+i.qty,0)} onClick={()=>{setCO(!co);setMO(false);}}/></div><HM isOpen={mo} setIsOpen={setMO} setCP={p=>{setCP(p);setCO(false);}} user={user}/><CD cart={cart} setCart={setCart} isOpen={co} setIsOpen={setCO}/>{rp()}<WAB/></div>);}